const input = [
  "Abnormal wound drainage (s_2369)",
"Abscess (s_598)",
"Absence of deep reflexes (s_1072)",
"Absence seizure (s_2047)",
"Absence seizures, reflex (s_2294)",
"Achilles tendon hyperreflexia (s_1502)",
"Acid reflux (s_2121)",
"Activity related to sex despite negative consequences (s_3)",
"Acute weight loss (s_2635)",
"Adenoid face (s_1111)",
"Agnosia (s_833)",
"Agoraphobia (s_884)",
"Agraphia (s_1012)",
"Alcohol craving (s_817)",
"Alcohol tolerance (s_588)",
"Alcohol withdrawal syndrome (s_818)",
"Allen-Cleckley sign (s_1272)",
"Allodynia (s_2648)",
"Alogia (s_837)",
"Amenorrhea, primary (s_1458)",
"Amenorrhea, secondary (s_1457)",
"Amenorrhea, secondary, 12 months or more (s_1370)",
"Amusia (s_1032)",
"Anger outbursts (s_660)",
"Angular cheilitis (s_608)",
"Anhedonia (s_508)",
"Anhedonia, lasting at least 2 weeks (s_287)",
"Anhidrosis (s_1123)",
"Anhidrosis, face, unilateral (s_669)",
"Anicteric presentation (s_2170)",
"Anisocoria (s_497)",
"Annular skin lesions (s_1647)",
"Anorectal pain (s_436)",
"Anuria (s_2586)",
"Anxiety (s_120)",
"Anxiety attack (s_582)",
"Apathy (s_4)",
"Aphonia (s_477)",
"Appetite for salty foods (s_6)",
"Apraxia (s_1010)",
"Ascites (s_1116)",
"Ataxia (s_651)",
"Ataxia, acute (s_2278)",
"Ataxia, chronic (s_2280)",
"Ataxia, subacute (s_2279)",
"Audible wheezing (s_474)",
"Auditory verbal agnosia (s_1028)",
"Auscultative fine crackles over the thorax (s_857)",
"Auscultative rhonchi over the thorax (s_1316)",
"Auscultative wheezes over the thorax (s_856)",
"Avoidance behaviour (s_2716)",
"Avoidance behaviour, trauma related (s_2705)",
"Avoiding eating in someone else's presence (s_719)",
"Avoiding eating or drinking in public (s_718)",
"Avoiding going home (s_2612)",
"Avoiding public appearances (s_717)",
"Avoiding talking to authority figures (s_720)",
"Axillary or inguinal freckles (s_1322)"
  ];
  
  const output = input.map(str => {
    const [name, id] = str.split(' (');
    return {
      id: id.replace(')', ''),
      name: name,
      choice_id: 'present'
    };
  });
  
  console.log(output);