const input = [
  "Babinski sign (s_1023)",
  "Back pain (s_1190)",
  "Back pain, exacerbated by physical exertion (s_159)",
  "Back pain, improves with rest (s_1206)",
  "Back pain, lasting several hours (s_1205)",
  "Back pain, lumbar (s_53)",
  "Back pain, lumbar, radiates to back of the thigh (s_38)",
  "Back pain, lumbar, radiating to the groin (s_663)",
  "Back pain, lumbar, unknown radiating direction (s_2314)",
  "Back pain, nocturnal (s_2284)",
  "Back pain, recurrent (s_1189)",
  "Back pain, severe (s_1192)",
  "Back pain, sudden (s_1198)",
  "Back pain, thoracic (s_1772)",
  "Back pain, worsens on palpation (s_2085)",
  "Bedwetting (s_2048)",
  "Belching (s_561)",
  "Bilateral absence of Achilles tendon reflex (s_1073)",
  "Bilateral enophthalmos (s_698)",
  "Bilateral muscle paralysis (s_1291)",
  "Bing's sign (s_1257)",
  "Binge eating (s_137)",
  "Binge eating, followed by self-disgust (s_568)",
  "Black coloured stool (s_71)",
  "Black stool, related to diet or medicine intake (s_2523)",
  "Bladder sphincter dysfunction (s_1119)",
  "Bleeding after intercourse (s_152)",
  "Bleeding from anus (s_115)",
  "Bleeding from anus, heavy (s_2277)",
  "Bleeding from anus, light (s_2276)",
  "Bleeding gums (s_111)",
  "Bleeding into muscles (s_1386)",
  "Blepharoptosis (s_192)",
  "Blepharoptosis, acute (s_2508)",
  "Blepharoptosis, chronic (s_2511)",
  "Blisters (s_1807)",
  "Blisters, bulla (s_1803)",
  "Blisters, vesicle (s_1804)",
  "Bloating (s_309)",
  "Blood glucose level, high (s_2012)",
  "Blood glucose level, low (s_2011)",
  "Blood glucose level, normal (s_2013)",
  "Blood glucose level, not measured (s_2014)",
  "Blood glucose level, very high (s_2482)",
  "Blood glucose level, very low (s_2487)",
  "Blood oxygen saturation, between 80% and 89% (s_2388)",
  "Blood oxygen saturation, between 90% and 94% (s_2387)",
  "Blood oxygen saturation, lower than 80% (s_2389)",
  "Blood oxygen saturation, normal (s_2376)",
  "Blood oxygen saturation, not measured (s_2375)",
  "Blood oxygen saturation, sudden worsening (s_2390)",
  "Blood pressure, between 140 and 179 mmHg (s_2408)",
  "Blood pressure, elevated (s_543)",
  "Blood pressure, more than 180 mmHg (s_1933)",
  "Blood pressure, normal or prehypertension (s_2272)",
  "Blood pressure, not measured (s_2273)",
  "Body aches (s_1835)",
  "Bone deformation, non-traumatic (s_2180)",
  "Bone deformation, post-traumatic (s_2181)",
];

const output = input.map((str) => {
  const [name, id] = str.split(" (");
  return {
    id: id.replace(")", ""),
    name: name,
    choice_id: "present",
  };
});

console.log(output);
